#!/usr/bin/env bash
# command to install nginx on my server

sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

# testing for nginx config
sudo nginx -t

sudo service nginx reload
