#!/usr/bin/env bash
# Nginx server redirects to another page, by Okpako Michael
# Update package repositories
sudo apt-get update

# Installing Nginx
sudo apt-get -y install nginx

# Create index.html with "Hello World!" content
echo "Hello World!" > /var/www/html/index.html

# Add redirect rule to Nginx configuration
sudo sed -i '/server_name _;/a \        return 301 https://github.com/mikelonia;' /etc/nginx/sites-enabled/default

# Restart Nginx service
sudo service nginx restart

