#!/usr/bin/env bash
# Nginx error 404 page, by Okpako Michael
sudo apt-get update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
string_forreplacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/mikelonia permanent;"

sudo sed -i "s/server_name _;/$string_forreplacement/" /etc/nginx/sites-enabled/default
#creating the 404 error page, by Okpako Michael
echo "Ceci n'est pasune page" | sudo tee /var/www/html/404.html
string_forreplacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/var/www/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_forreplacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
