#!/usr/bin/env bash
# debugging nginx port 80
# How did I solve it ?: This is the step ; 1. delete the existing ../ 2 sites-enabled/default and replace it with a cop
# ../sites-available/default. You do that by creating a symbolic link. 
# NB: The flag -s is creating a symbolic link, -f deletes the existing file and replaces it
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
