#!/usr/bin/env bash
# Script that displays numbers from 1 to 100
# displays FizzBuzz when the number is a multiple of 3 and 5
# displays Fizz when the number is a multiple of 3
# displays Buzz when the number is a multiple of 5
# otherwise, displays the number in a list format
m=1
while [ $m -le 100 ]
do
	if [ $((m % 5)) == 0 ] && [ $((m % 3)) == 0 ]
	then
		echo "FizzBuzz"
	elif [ $((m % 3)) == 0 ]
	then
		echo "Fizz"
	elif [ $((m % 5)) == 0 ]
	then
		echo "Buzz"
	else
		echo "$m"
	fi
	m=$(( m + 1 ))
done	
