#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# but for the 9th iteration displays "Best School" and then "Hi"
m=1
while [ $i -le 10 ]
do
	if [ $m = 10 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	m=$(( m + 1 ))
done
