#!/usr/bin/env bash
# This script loops from 1 to 20 and:
# displays 4 and then bad luck from China for the 4th iteration
# displays 9 and then bad luck from Japan for the 8th iteraion
# displays 17 and then bad luck from Italy for the 17th iteration
m=1
while [ $m -le 20 ]
do
	case $m in
		4)
			echo "$m"
			echo "bad luck from China"
			;;
		9)
			echo "$m"
			echo "bad luck from Japan"
			;;
		17)
			echo "$m"
			echo "bad luck from Italy"
			;;
		*)
			echo "$m"
			;;
	esac
	m=$(( m + 1 ))
done
