#!/usr/bin/env bash
# Display the time for 12 hours and 59 minutes
# display hours from 0 to 12
# display minutes from 1 to 59
hours=0
while [ $hours -le 12 ]
do
	echo "Hour: $hours"
	m=1
	while [ $m -le 59 ]
	do
		echo "$m"
		m=$(( m + 1 ))
	done
	hours=$(( hours + 1 ))
done
