#!/usr/bin/env bash
# Script that configures an Ubuntu server
# Configure localhost resolution
echo "127.0.0.2 localhost" >> /etc/hosts

# Configure facebook.com resolution
echo "8.8.8.8 facebook.com" >> /etc/hosts

