#!/usr/bin/env bash
# This script accepts a username as an argument and runs the whoami command under that us
# A Bash script that runs the whoami command on the the first argument passed
# to it. Here am assumming the first command passed to the script is a user
# registerred on the system.
sudo -u "$1" whoami
